### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by alexandru-dinu** [alexandru-dinu/vertical-search#1]
## Initial stage

**Crawler**
- [x] extract title, authors, pdf, abstract from articles in a field (e.g. AI / IR) - start with arXiv
- [x] construct a `Paper` node from this info
- [x] indexer: see https://whoosh.readthedocs.io/en/latest/index.html
- [x] searcher

**Query resolution**
- [x] final result: list of articles (top-N), **ranked** by relevance (TF-IDF)
- query types:
  - `(lstm OR gru) AND attention` (boolean)
  - `(written by: xyz) and (cited by: abc) and (author pos <= 2)` (considering graph idea)

**Ideas**
- [ ] if an unknown keyword is encountered in a query, find closest concepts of that keyword and refine the search
- [ ] construct citation graph: `Vertices = {papers p}, Edges = {(p, r), ∀ r ∈ ref(p)}`
- [ ] starting from several *seeds*, explore the graph to find similar papers
- [ ] intermediate step: return sub-graph with matching criteria

**Comment by alexandru-dinu** [comment]
## Final stage
- [ ] graph representation
  - [ ] special semantics for what an edge represents (e.g. written-by, published-in etc.)
  - [ ] apply ranking algorithms similar to PageRank, as a way of measuring the importance of a paper
  - PageRank only makes sense on a citation graph
- [ ] simple misspelling corrector (*Did you mean ... ?*)
- [x] mechanism for retrieving the matched query in the title / abstract text (*needle in haystack*)
- [ ] querying the position of authors (e.g. main author / advisor, assuming relative contribution)
- [ ] relevant set of query examples
- [x] keyword extraction using TF-IDF
---
### Tried
- [x] extract references of a paper: `ref(p)`
  - refextract / pdfminer / pdfbox; it's very messy
- [x]  augment the scoring mechanism to also take into account the number of citations
  - sent requests to Google Scholar; kinda inefficient + no results for some articles
